name: Run JS with Secret

on: [push]

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Run script.js with secret
        run: node script.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
